# Generated by Django 4.2.5 on 2023-09-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_category_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
