# Generated by Django 4.2.5 on 2023-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variation_variation_category_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
