# Generated by Django 4.2.5 on 2023-09-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_percent',
        ),
    ]
