# Generated by Django 4.2.5 on 2023-09-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
